dist: trusty

language: cpp

env:
  global:
  - DOCKER_CONTAINER: cmssw/slc6-base:latest

branches:
  only:
  - /.*/

before_install:
- sudo apt-get -qq update
- sudo apt-get install -qq autofs attr gdb git uuid-dev uuid fuse
- wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
- sudo dpkg -i cvmfs-release-latest_all.deb
- sudo apt-get update
- sudo apt-get install -qq cvmfs cvmfs-config-default
- sudo cvmfs_config setup
- sudo echo "CVMFS_HTTP_PROXY=\"DIRECT\"" | sudo tee /etc/cvmfs/default.local > /dev/null
- sudo echo CVMFS_REPOSITORIES=cms.cern.ch | sudo tee -a /etc/cvmfs/default.local > /dev/null
- sudo service autofs restart
- cvmfs_config probe
- sudo cvmfs_config chksetup
- sudo docker pull $DOCKER_CONTAINER

compiler:
- gcc

script:
- chmod +x $TRAVIS_BUILD_DIR/travisScript.sh
- sudo docker run -v /cvmfs:/cvmfs -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR $DOCKER_CONTAINER $TRAVIS_BUILD_DIR/travisScript.sh $TRAVIS_BUILD_DIR

notifications:
  email: false
