dist: trusty

language: cpp

env:
  global:
  - DOCKER_CONTAINER: aperloff/cms-cvmfs-docker:latest

branches:
  only:
  - /.*/

before_install:
- sudo docker pull $DOCKER_CONTAINER

compiler:
- gcc

script:
- chmod +x $TRAVIS_BUILD_DIR/.travis/travisScript.sh
- sudo docker run -it -P --device /dev/fuse --cap-add SYS_ADMIN -e CVMFS_MOUNTS="cms.cern.ch oasis.opensciencegrid.org" -e MY_UID=$(id -u) -e MY_GID=$(id -g) -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR $DOCKER_CONTAINER $TRAVIS_BUILD_DIR/.travis/travisScript.sh $TRAVIS_BUILD_DIR 

notifications:
  email: false
